Repository wp-cli/checksum-command, pull requests merged in 2018-04, with the labels that each got.

#42 Raise memory limit to 2048MB
  .travis.yml
Labels: bug, scope:testing

#43 Make soft changes more flexible for plugin checksums
  features/checksum-plugin.feature
  src/Checksum_Plugin_Command.php
Labels: command:plugin-verify-checksums

#44 Update scaffolded files
  bin/test.sh
  features/bootstrap/FeatureContext.php
  features/bootstrap/Process.php
  features/bootstrap/utils.php
  utils/behat-tags.php
Labels: scope:testing
