Repository wp-cli/checksum-command, pull requests merged in 2019-04, with the labels that each got.

#59 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#62 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  checksum-command.php
  composer.json
  phpcs.xml.dist
  src/Checksum_Base_Command.php
  src/Checksum_Core_Command.php
  src/Checksum_Plugin_Command.php
  src/WP_CLI/Fetchers/UnfilteredPlugin.php
Labels: command:core-verify-checksums, command:plugin-verify-checksums

#63 Update README.md file
  README.md
Labels: scope:documentation
