Repository wp-cli/checksum-command, pull requests merged in 2023-02, with the labels that each got.

#99 Fix failing checksum tests due to timeout on `WP_VERSION=trunk`
  features/checksum-core.feature
Labels: bug, scope:testing

#97 Replace empty namespace autoloader with classmap
  composer.json
Labels: scope:distribution

#98 Add `composer phpcbf` and allow `wordpress-core-installer`
  composer.json
Labels: scope:testing
